vich_uploader:
    db_driver: orm
    mappings:
        theme_images:
            uri_prefix:         '%app.path.theme_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.theme_images%'