monolog:
    handlers:
        main:
            type: rotating_file
            action_level: error
            level: debug
            handler: nested
            max_files: 10
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]

