settings:
    index:
        # single node, no sharding
        number_of_shards: 1
        number_of_replicas: 0
mappings:
    article:
        dynamic: false # disable dynamic mapping
        properties:
            title: &fr_text
                type: text
                analyzer: french
            author: *fr_text
            tags: &fr_text
                type: text
                fielddata: true
            content: *fr_text
            comments: *fr_text